### ISSUE TITLE
`pillow>3.0.0` causes segfault on `Image.resize` on `win-32` with `freetype<2.8`

### ISSUE THREAD

**Issue by cfobel** [conda-forge/pillow-feedstock#39] opened 2018-01-03 16:37 UTC
# Setup

 1. Install `pillow`:

        conda install -c conda-forge pillow
 2. Run the following script (download here: [pillow-test.zip][pytest]):

    ```python
    import io
    import urllib

    from PIL import Image


    # Load test image
    URL = 'https://upload.wikimedia.org/wikipedia/commons/a/a9/256x256_Single.png'
    image_data = io.BytesIO(urllib.urlopen(URL).read())
    image = Image.open(image_data)

    # Test resize of image
    image.resize((300, 500))
    ```

# Expected behaviour

 - `pillow==4.3.0` is installed (as of 2018-01-03)
 - Image resized (in memory).

# Observed behaviour

 - `pillow==4.3.0` is installed (as of 2018-01-03)
 - Segmentation fault occurs during resize operation, resulting in the following error dialog:  
 
    ![image](https://user-images.githubusercontent.com/823355/34529103-eecfa0da-f078-11e7-89a0-0ab8d8d43539.png)

# Workaround

Install `pillow==3.0.0` with `freetype>=2.8`:

    conda install -c conda-forge pillow

--------------------------------------------------------------------------------

# Notes

This seems to be an issue related to both the version of `pillow` *and* `freetype`.

To help reproduce the issue, I have attached some exported Conda environments below.  To test an environment:

 1. Extract environment and run:

        conda env create -f <environment name>.yaml
 2. Extract and run the [test Python script][pytest]:

        python pillow-test.py

Environments:
 - **Fails**: [env-pillow-3.0.0-py27-x86.yaml.zip](https://github.com/conda-forge/pillow-feedstock/files/1600995/env-pillow-3.0.0-py27-x86.yaml.zip)
 - **Fails**: [env-pillow-4-py27-x86.zip](https://github.com/conda-forge/pillow-feedstock/files/1600996/env-pillow-4-py27-x86.zip)
 - **Passes**: [env-pillow-3.0.0-freetype-2.8-py27-x86.yaml.zip](https://github.com/conda-forge/pillow-feedstock/files/1600997/env-pillow-3.0.0-freetype-2.8-py27-x86.yaml.zip)

[pytest]: https://github.com/conda-forge/pillow-feedstock/files/1601004/pillow-test.zip

**Comment by ocefpaf** [comment] 2018-01-09 10:50
Thanks for the report! Latest pillow uses freetype 2.8, can you ensure that you got build number 2 in your tests? I'll add you script to the test section in a PR soon to investigate that.

**Comment by cfobel** [comment] 2018-01-09 15:12
Thanks for your response @ocefpaf !

According to the following output from `conda list`, version `freetype 2.8.1 vc9_0  [vc9]` is installed from the `conda-forge` channel.  This agrees with the latest version listed [in the `conda-forge` channel (as of 2018.01.09)][conda-forge].  Note that this package version seems to have a build number of 0 (i.e., vc9_**0**).  Should there be another package version listed with a build number of **2**?  Is this what you mean?

```
> conda list
# packages in environment at ...\pillow-test:
#
certifi                   2017.11.5                py27_0    conda-forge
freetype                  2.8.1                     vc9_0  [vc9]  conda-forge
jpeg                      9b                        vc9_2  [vc9]  conda-forge
libpng                    1.6.34                    vc9_0  [vc9]  conda-forge
libtiff                   4.0.9                     vc9_0  [vc9]  conda-forge
olefile                   0.44                     py27_0    conda-forge
pillow                    4.3.0                    py27_2    conda-forge
pip                       9.0.1                    py27_1    conda-forge
python                    2.7.14                        4    conda-forge
setuptools                38.4.0                   py27_0    conda-forge
vc                        9                             0    conda-forge
vs2008_runtime            9.0.30729.6161                0    conda-forge
wheel                     0.30.0                   py27_2    conda-forge
wincertstore              0.2                      py27_0    conda-forge
zlib                      1.2.11                    vc9_0  [vc9]  conda-forge
```

[conda-forge]: https://anaconda.org/conda-forge/freetype/files

**Comment by ocefpaf** [comment] 2018-01-09 16:38
> Note that this package version seems to have a build number of 0 (i.e., vc9_**0**).  Should there be another package version listed with a build number of **2**?  Is this what you mean?

No, I meant build number **2** for `pillow` and you do have that there. Note that I was unable to reproduce the issue with AppVeyor, see #40 

I'll try to find a Windows machine and see if I can test that locally.

**Comment by ocefpaf** [comment] 2018-01-09 16:55
With a new env (`conda create --name TEST python=2.7 pillow`) everything worked for me 😕 

Here is my `conda list`. Closing b/c I cannot reproduce it, maybe it is something we can fix or maybe it is on your system...

```
(TEST) C:\Users\filipe>conda list
# packages in environment at C:\Users\filipe\Miniconda3\envs\TEST:
#
certifi                   2017.11.5                py27_0    conda-forge
freetype                  2.8.1                     vc9_0  [vc9]  conda-forge
jpeg                      9b                        vc9_2  [vc9]  conda-forge
libpng                    1.6.34                    vc9_0  [vc9]  conda-forge
libtiff                   4.0.9                     vc9_0  [vc9]  conda-forge
olefile                   0.44                     py27_0    conda-forge
pillow                    4.3.0                    py27_2    conda-forge
pip                       9.0.1                    py27_1    conda-forge
python                    2.7.14                        4    conda-forge
setuptools                38.4.0                   py27_0    conda-forge
vc                        9                             0    conda-forge
vs2008_runtime            9.0.30729.6161                0    conda-forge
wheel                     0.30.0                   py27_2    conda-forge
wincertstore              0.2                      py27_0    conda-forge
zlib                      1.2.11                    vc9_0  [vc9]  conda-forge
```

**Closed by ocefpaf** 2018-01-09 16:55 UTC

**Comment by cfobel** [comment] 2018-01-09 18:38
@ocefpaf , thanks for testing this.  Can you please confirm that you were testing in a `win-32` installation?  I did not see this issue when running in a `win-64` installation.

**Comment by ocefpaf** [comment] 2018-01-09 18:49
>  Can you please confirm that you were testing in a `win-32` installation?  I did not see this issue when running in a `win-64` installation.

My local testing was in a `win-64` machine, but AppVeyor tested both.
